import { v4 as uuid } from "uuid";


export const products = [
  {
    _id: "1",
    img: "product1.jpg",
    name: "Fresh Apples",
    author: "Local Farmers",
    price: 2.99,
    originalPrice: 3.99,
    isBestSeller: false,
    category: "Fruits and Vegetables",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Fresh Produce"
  },
  {
    _id: "2",
    img: "rice.jpg",
    name: "Long Grain Rice",
    author: "Rural Grains",
    price: 2.99,
    originalPrice: 3.99,
    isBestSeller: false,
    category: "Grains and Cereals",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Wholesome Grains"
  },
  {
    _id: "3",
    img: "product3.jpg",
    name: "Farmhouse Cheddar Cheese",
    author: "Dairy Delights",
    price: 4.49,
    originalPrice: 5.99,
    isBestSeller: true,
    category: "Dairy Products",
    rating: 4.7,
    delivery: "2-4 days",
    categoryTitle: "Artisanal Cheese"
  },
  {
    _id: "4",
    img: "product4.jpg",
    name: "Grass-Fed Ground Beef",
    author: "Happy Farms",
    price: 8.99,
    originalPrice: 10.99,
    isBestSeller: false,
    category: "Meat and Poultry",
    rating: 4.6,
    delivery: "3-5 days",
    categoryTitle: "Premium Meats"
  },
  {
    _id: "5",
    img: "product5.jpg",
    name: "Organic Basil",
    author: "Herb Haven",
    price: 1.99,
    originalPrice: 2.99,
    isBestSeller: false,
    category: "Herbs and Spices",
    rating: 4.3,
    delivery: "1-3 days",
    categoryTitle: "Aromatic Herbs"
  },
  {
    _id: "6",
    img: "corn.jpg",
    name: "Fresh Sweet Corn",
    author: "Golden Harvest",
    price: 0.99,
    originalPrice: 1.29,
    isBestSeller: true,
    category: "Grains and Cereals",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Seasonal Delight"
  },
  {
    _id: "7",
    img: "product7.jpg",
    name: "Mixed Bouquet",
    author: "Blooming Fields",
    price: 9.99,
    originalPrice: 12.99,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.7,
    delivery: "1-2 days",
    categoryTitle: "Fresh Blooms"
  },
  {
    _id: "8 ",
    img: "beef.jpg",
    name: "Grass-Fed Beef",
    author: "Natural Farms",
    price: 12.99,
    originalPrice: 14.99,
    isBestSeller: true,
    category: "Meat and Poultry",
    rating: 4.8,
    delivery: "1-2 days",
    categoryTitle: "Premium Cuts"
  },
  {
    _id: "9",
    img: "oregano.jpg",
    name: "Dried Oregano",
    author: "Spice Masters",
    price: 1.49,
    originalPrice: 1.99,
    isBestSeller: true,
    category: "Herbs and Spices",
    rating: 4.7,
    delivery: "1-2 days",
    categoryTitle: "Flavorful Spices"
  },
  {
    _id: "10",
    img: "tulip.jpg",
    name: "Colorful Tulip Bulbs",
    author: "Blossom Fields",
    price: 5.99,
    originalPrice: 7.99,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Elegant Tulips"
  },
  {
    _id: "11",
    img: "tomato.jpg",
    name: "Vine-Ripened Tomatoes",
    author: "Harvest Farms",
    price: 3.49,
    originalPrice: 3.99,
    isBestSeller: true,
    category: "Fruits and Vegetables",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Freshly Harvested"
  },
  {
    _id: "12",
    img: "product12.jpg",
    name: "Juicy Oranges",
    author: "Citrus Farms",
    price: 3.49,
    originalPrice: 4.49,
    isBestSeller: false,
    category: "Fruits and Vegetables",
    rating: 4.7,
    delivery: "2-3 days",
    categoryTitle: "Vitamin C Boost"
  },
  {
    _id: "13",
    img: "product13.jpg",
    name: "Brown Rice",
    author: "Rural Grains",
    price: 2.99,
    originalPrice: 3.99,
    isBestSeller: false,
    category: "Grains and Cereals",
    rating: 4.6,
    delivery: "1-3 days",
    categoryTitle: "Wholesome Grains"
  },
  {
    _id: "14",
    img: "product14.jpg",
    name: "Farm Fresh Milk",
    author: "Dairy Delights",
    price: 2.49,
    originalPrice: 2.99,
    isBestSeller: true,
    category: "Dairy Products",
    rating: 4.8,
    delivery: "2-4 days",
    categoryTitle: "Creamy Goodness"
  },
  {
    _id: "15",
    img: "product15.jpg",
    name: "Tender Lamb Chops",
    author: "Happy Farms",
    price: 11.99,
    originalPrice: 14.99,
    isBestSeller: true,
    category: "Meat and Poultry",
    rating: 4.7,
    delivery: "3-5 days",
    categoryTitle: "Succulent Meats"
  },
  {
    _id: "16",
    img: "product16.jpg",
    name: "Dried Thyme",
    author: "Herb Haven",
    price: 1.49,
    originalPrice: 1.99,
    isBestSeller: false,
    category: "Herbs andSpices",
    rating: 4.4,
    delivery: "1-2 days",
    categoryTitle: "Flavorful Herbs"
  },
  {
    _id: "17",
    img: "turmeric.jpg",
    name: "Ground Turmeric",
    author: "Curry House",
    price: 2.99,
    originalPrice: 3.99,
    isBestSeller: true,
    category: "Herbs and Spices",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Vibrant Spices"
  },
  {
    _id: "18",
    img: "product18.jpg",
    name: "Colorful Mixed Flowers",
    author: "Blooming Fields",
    price: 14.99,
    originalPrice: 17.99,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.9,
    delivery: "1-2 days",
    categoryTitle: "Vibrant Blooms"
  },
  {
    _id: "19",
    img: "wheat.jpg",
    name: "Whole Wheat Flour",
    author: "Mills & Co.",
    price: 4.99,
    originalPrice: 5.99,
    isBestSeller: true,
    category: "Grains and Cereals",
    rating: 4.8,
    delivery: "1-2 days",
    categoryTitle: "Nutritious Staples"
  },
  {
    _id: "20",
    img: "basil.jpg",
    name: "Fresh Basil Leaves",
    author: "Herb Haven",
    price: 1.99,
    originalPrice: 2.49,
    isBestSeller: false,
    category: "Herbs and Spices",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Aromatic Herbs"
  }
];
