import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://www.shutterstock.com/image-photo/red-apple-isolated-on-white-600w-1727544364.jpg",
    name: "Fresh Apples",
    author: "Local Farmers",
    price: 299,
    originalPrice: 399,
    isBestSeller: false,
    category: "Fruits and Vegetables",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Fresh Produce"
  },
  {
    _id: uuid(),
    img: "https://media.istockphoto.com/id/153737841/photo/rice.jpg?s=612x612&w=0&k=20&c=lfO7iLT0UsDDzra0uBOsN1rvr2d5OEtrG2uwbts33_c=",
    name: "Long Grain Rice",
    author: "Rural Grains",
    price: 499,
    originalPrice: 699,
    isBestSeller: false,
    category: "Grains and Cereals",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Wholesome Grains"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs08D9ve4-v8eKr-winYIIfPL461NbCnxIgQ&usqp=CAU",
    name: "Farmhouse Cheddar Cheese",
    author: "Dairy Delights",
    price: 449,
    originalPrice: 599,
    isBestSeller: true,
    category: "Dairy Products",
    rating: 4.7,
    delivery: "2-4 days",
    categoryTitle: "Artisanal Cheese"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcMjzy3Sbs-Yty20rNPXotOrZ_7RFkr8qHyw&usqp=CAU",
    name: "Grass-Fed Ground Beef",
    author: "Happy Farms",
    price: 899,
    originalPrice: 1099,
    isBestSeller: false,
    category: "Meat and Poultry",
    rating: 4.6,
    delivery: "3-5 days",
    categoryTitle: "Premium Meats"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgdTpHlGykJyiyE2bNxcvIFGzHaPrl-zZY1A&usqp=CAU",
    name: "Organic Basil",
    author: "Herb Haven",
    price: 199,
    originalPrice: 299,
    isBestSeller: false,
    category: "Herbs and Spices",
    rating: 4.3,
    delivery: "1-3 days",
    categoryTitle: "Aromatic Herbs"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR9ZaDV4KkglS6bIkFnB-U4hMIW6v8wfiFjw&usqp=CAU",
    name: "Fresh Sweet Corn",
    author: "Golden Harvest",
    price: 199,
    originalPrice: 229,
    isBestSeller: true,
    category: "Grains and Cereals",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Seasonal Delight"
  },
  {
    _id: uuid(),
    img: "https://flowersnfruits-image.s3.ap-south-1.amazonaws.com/uploads/product-pics/mix-color-roses-bouquet.jpg",
    name: "Mixed Bouquet",
    author: "Blooming Fields",
    price: 999,
    originalPrice: 1299,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.7,
    delivery: "1-2 days",
    categoryTitle: "Fresh Blooms"
  },
  {
    _id: uuid(),
    img: "beef.jpg",
    name: "Grass-Fed Beef",
    author: "Natural Farms",
    price: 1299,
    originalPrice: 1499,
    isBestSeller: true,
    category: "Meat and Poultry",
    rating: 4.8,
    delivery: "1-2 days",
    categoryTitle: "Premium Cuts"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0Gh5bUO-8tWjFDuC1u8ZyP3O_XCPPM0lDFg&usqp=CAU",
    name: "Dried Oregano",
    author: "Spice Masters",
    price: 149,
    originalPrice: 199,
    isBestSeller: true,
    category: "Herbs and Spices",
    rating: 4.7,
    delivery: "1-2 days",
    categoryTitle: "Flavorful Spices"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLsZVzrlG-sN5MtSjqXIBQJbcmWmqXC8F9b9d7R-3-Q3AfdfwuHxfkxpOxAiDuPpxz81c&usqp=CAU",
    name: "Colorful Tulip Bulbs",
    author: "Blossom Fields",
    price: 599,
    originalPrice: 799,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Elegant Tulips"
  },
  {
    _id: uuid(),
    img: "https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/three-vine-ripened-tomatoes-scott-hales.jpg",
    name: "Vine-Ripened Tomatoes",
    author: "Harvest Farms",
    price: 349,
    originalPrice: 399,
    isBestSeller: true,
    category: "Fruits and Vegetables",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Freshly Harvested"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPpdOh7Kql4SSNAP8ZENiOe_3evpZyaH95JA&usqp=CAU",
    name: "Juicy Oranges",
    author: "Citrus Farms",
    price: 349,
    originalPrice: 449,
    isBestSeller: false,
    category: "Fruits and Vegetables",
    rating: 4.7,
    delivery: "2-3 days",
    categoryTitle: "Vitamin C Boost"
  },
  {
    _id: uuid(),
    img: "https://media.istockphoto.com/id/173589620/photo/brown-rice.jpg?s=612x612&w=0&k=20&c=yvu1W2c5fj1Aa6lb-NvWQPXXmL__QWJqS2kGlhCfq0I=",
    name: "Brown Rice",
    author: "Rural Grains",
    price: 299,
    originalPrice: 399,
    isBestSeller: false,
    category: "Grains and Cereals",
    rating: 4.6,
    delivery: "1-3 days",
    categoryTitle: "Wholesome Grains"
  },
  {
    _id: uuid(),
    img: "https://tiimg.tistatic.com/fp/1/007/457/natural-farm-fresh-delicious-flavour-100-pure-cow-milk-for-human-consumption-692.jpg",
    name: "Farm Fresh Milk",
    author: "Dairy Delights",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: "Dairy Products",
    rating: 4.8,
    delivery: "2-4 days",
    categoryTitle: "Creamy Goodness"
  },
  {
    _id: uuid(),
    img: "product15.jpg",
    name: "Tender Lamb Chops",
    author: "Happy Farms",
    price: 199,
    originalPrice: 229,
    isBestSeller: true,
    category: "Meat and Poultry",
    rating: 4.7,
    delivery: "3-5 days",
    categoryTitle: "Succulent Meats"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1AH0pSgB-hnQrWHO_RIFrTxbueeVgJgYOxg&usqp=CAU",
    name: "Dried Thyme",
    author: "Herb Haven",
    price: 149,
    originalPrice: 199,
    isBestSeller: false,
    category: "Herbs andSpices",
    rating: 4.4,
    delivery: "1-2 days",
    categoryTitle: "Flavorful Herbs"
  },
  {
    _id: uuid(),
    img: "https://5.imimg.com/data5/CC/AQ/MY-48498942/organic-haldi-powder-500x500.jpg",
    name: "Ground Turmeric",
    author: "Curry House",
    price: 299,
    originalPrice: 399,
    isBestSeller: true,
    category: "Herbs and Spices",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Vibrant Spices"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPHCuezF9kW78FRtxz_8tph5qamTnnbfwlfw&usqp=CAU",
    name: "Rose",
    author: "Blooming Fields",
    price: 149,
    originalPrice: 179,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.9,
    delivery: "1-2 days",
    categoryTitle: "Vibrant Blooms"
  },
  {
    _id: uuid(),
    img: "https://media.istockphoto.com/id/153162703/photo/flour-in-small-burlap-sack.jpg?s=612x612&w=0&k=20&c=mEROV4y5JVyhweys6UjROtl7sUdgPZOvTIP7cBMbxD0=",
    name: "Whole Wheat Flour",
    author: "Mills & Co.",
    price: 499,
    originalPrice: 599,
    isBestSeller: true,
    category: "Grains and Cereals",
    rating: 4.8,
    delivery: "1-2 days",
    categoryTitle: "Nutritious Staples"
  },
  {
    _id: uuid(),
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUcne9Vy7KKs_UMuR7x051ROJlDSY-tLlu7g&usqp=CAU",
    name: "Fresh Basil Leaves",
    author: "Herb Haven",
    price: 199,
    originalPrice: 249,
    isBestSeller: false,
    category: "Herbs and Spices",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Aromatic Herbs"
  }
];
