import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://www.shutterstock.com/image-photo/red-apple-isolated-on-white-600w-1727544364.jpg",
    name: "Fresh Apples",
    author: "Local Farmers",
    price: 299,
    originalPrice: 399,
    isBestSeller: false,
    category: "Fruits and Vegetables",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Fresh Produce"
  },
  {
    _id: uuid(),
    img: "rice.jpg",
    name: "Long Grain Rice",
    author: "Rural Grains",
    price: 499,
    originalPrice: 699,
    isBestSeller: false,
    category: "Grains and Cereals",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Wholesome Grains"
  },
  {
    _id: uuid(),
    img: "product3.jpg",
    name: "Farmhouse Cheddar Cheese",
    author: "Dairy Delights",
    price: 449,
    originalPrice: 599,
    isBestSeller: true,
    category: "Dairy Products",
    rating: 4.7,
    delivery: "2-4 days",
    categoryTitle: "Artisanal Cheese"
  },
  {
    _id: uuid(),
    img: "product4.jpg",
    name: "Grass-Fed Ground Beef",
    author: "Happy Farms",
    price: 899,
    originalPrice: 1099,
    isBestSeller: false,
    category: "Meat and Poultry",
    rating: 4.6,
    delivery: "3-5 days",
    categoryTitle: "Premium Meats"
  },
  {
    _id: uuid(),
    img: "product5.jpg",
    name: "Organic Basil",
    author: "Herb Haven",
    price: 199,
    originalPrice: 299,
    isBestSeller: false,
    category: "Herbs and Spices",
    rating: 4.3,
    delivery: "1-3 days",
    categoryTitle: "Aromatic Herbs"
  },
  {
    _id: uuid(),
    img: "corn.jpg",
    name: "Fresh Sweet Corn",
    author: "Golden Harvest",
    price: 199,
    originalPrice: 229,
    isBestSeller: true,
    category: "Grains and Cereals",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Seasonal Delight"
  },
  {
    _id: uuid(),
    img: "product7.jpg",
    name: "Mixed Bouquet",
    author: "Blooming Fields",
    price: 999,
    originalPrice: 1299,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.7,
    delivery: "1-2 days",
    categoryTitle: "Fresh Blooms"
  },
  {
    _id: uuid(),
    img: "beef.jpg",
    name: "Grass-Fed Beef",
    author: "Natural Farms",
    price: 1299,
    originalPrice: 1499,
    isBestSeller: true,
    category: "Meat and Poultry",
    rating: 4.8,
    delivery: "1-2 days",
    categoryTitle: "Premium Cuts"
  },
  {
    _id: uuid(),
    img: "oregano.jpg",
    name: "Dried Oregano",
    author: "Spice Masters",
    price: 149,
    originalPrice: 199,
    isBestSeller: true,
    category: "Herbs and Spices",
    rating: 4.7,
    delivery: "1-2 days",
    categoryTitle: "Flavorful Spices"
  },
  {
    _id: uuid(),
    img: "tulip.jpg",
    name: "Colorful Tulip Bulbs",
    author: "Blossom Fields",
    price: 599,
    originalPrice: 799,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Elegant Tulips"
  },
  {
    _id: uuid(),
    img: "tomato.jpg",
    name: "Vine-Ripened Tomatoes",
    author: "Harvest Farms",
    price: 349,
    originalPrice: 399,
    isBestSeller: true,
    category: "Fruits and Vegetables",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Freshly Harvested"
  },
  {
    _id: uuid(),
    img: "product12.jpg",
    name: "Juicy Oranges",
    author: "Citrus Farms",
    price: 349,
    originalPrice: 449,
    isBestSeller: false,
    category: "Fruits and Vegetables",
    rating: 4.7,
    delivery: "2-3 days",
    categoryTitle: "Vitamin C Boost"
  },
  {
    _id: uuid(),
    img: "product13.jpg",
    name: "Brown Rice",
    author: "Rural Grains",
    price: 299,
    originalPrice: 399,
    isBestSeller: false,
    category: "Grains and Cereals",
    rating: 4.6,
    delivery: "1-3 days",
    categoryTitle: "Wholesome Grains"
  },
  {
    _id: uuid(),
    img: "product14.jpg",
    name: "Farm Fresh Milk",
    author: "Dairy Delights",
    price: 249,
    originalPrice: 299,
    isBestSeller: true,
    category: "Dairy Products",
    rating: 4.8,
    delivery: "2-4 days",
    categoryTitle: "Creamy Goodness"
  },
  {
    _id: uuid(),
    img: "product15.jpg",
    name: "Tender Lamb Chops",
    author: "Happy Farms",
    price: 199,
    originalPrice: 229,
    isBestSeller: true,
    category: "Meat and Poultry",
    rating: 4.7,
    delivery: "3-5 days",
    categoryTitle: "Succulent Meats"
  },
  {
    _id: uuid(),
    img: "product16.jpg",
    name: "Dried Thyme",
    author: "Herb Haven",
    price: 149,
    originalPrice: 199,
    isBestSeller: false,
    category: "Herbs andSpices",
    rating: 4.4,
    delivery: "1-2 days",
    categoryTitle: "Flavorful Herbs"
  },
  {
    _id: uuid(),
    img: "turmeric.jpg",
    name: "Ground Turmeric",
    author: "Curry House",
    price: 299,
    originalPrice: 399,
    isBestSeller: true,
    category: "Herbs and Spices",
    rating: 4.6,
    delivery: "2-4 days",
    categoryTitle: "Vibrant Spices"
  },
  {
    _id: uuid(),
    img: "product18.jpg",
    name: "Colorful Mixed Flowers",
    author: "Blooming Fields",
    price: 149,
    originalPrice: 179,
    isBestSeller: true,
    category: "Flowers and Plants",
    rating: 4.9,
    delivery: "1-2 days",
    categoryTitle: "Vibrant Blooms"
  },
  {
    _id: uuid(),
    img: "wheat.jpg",
    name: "Whole Wheat Flour",
    author: "Mills & Co.",
    price: 499,
    originalPrice: 599,
    isBestSeller: true,
    category: "Grains and Cereals",
    rating: 4.8,
    delivery: "1-2 days",
    categoryTitle: "Nutritious Staples"
  },
  {
    _id: uuid(),
    img: "basil.jpg",
    name: "Fresh Basil Leaves",
    author: "Herb Haven",
    price: 199,
    originalPrice: 249,
    isBestSeller: false,
    category: "Herbs and Spices",
    rating: 4.5,
    delivery: "2-3 days",
    categoryTitle: "Aromatic Herbs"
  }
];
